language: java

notifications:
  email: false

env:
  - NODE_VERSION=v7.10.0

install:
  - nvm install "${NODE_VERSION}";
    nvm use "${NODE_VERSION}";
    cd "${TRAVIS_BUILD_DIR}/client";
    npm install;

before_script:
  - export CLIENT_DIR="${TRAVIS_BUILD_DIR}/client";
  - export SERVER_DIR="${TRAVIS_BUILD_DIR}/server/eclipse-project";

script:
  # WARNING: If changes only occur in files outside of the checked
  # directory, the checks below will not be executed.
  - if ${TRAVIS_BUILD_DIR}/ci/changes-in-dir client; then
      cd "${CLIENT_DIR}";
      npm run lint;
      npm run build;
      npm test;
    fi;

  # WARNING: If changes only occur in files outside of the checked
  # directory, the checks below will not be executed.
  - if ${TRAVIS_BUILD_DIR}/ci/changes-in-dir server; then
      cd "${SERVER_DIR}";
      mvn verify;
    fi;
